# based on
# https://github.com/lucasrla/shynet-docker-lightsail/blob/master/docker-compose.yml

version: '1'

services:
  shynet:
    image: milesmcc/shynet:latest
    restart: unless-stopped
    # https://stackoverflow.com/questions/40801772/what-is-the-difference-between-docker-compose-ports-vs-expose
    expose:
      - 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    networks:
      - internal
    depends_on:
      - db
  db:
    image: "postgres:12"
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    volumes:
      - shynet_db:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  shynet_db:

networks:
  internal:  
